services:
  youtrack:
    image: jetbrains/youtrack:2025.3.108480
    container_name: youtrack-server
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - /opt/youtrack/data:/opt/youtrack/data
      - /opt/youtrack/conf:/opt/youtrack/conf
      - /opt/youtrack/logs:/opt/youtrack/logs
      - /opt/youtrack/backups:/opt/youtrack/backups
    restart: unless-stopped
